name = "sleep-calculator"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2024-06-20"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
zone_id = "YOUR_ZONE_ID"
route = "sleep-time-calculator.com/*"